################################################################
# Global configuration
################################################################

debug = false
logLevel = "ERROR"

defaultEntryPoints = ["http"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"

  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
[retry]

################################################################
# Docker configuration backend
################################################################

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedByDefault = false
swarmMode = true

################################################################
# Let's Encrypt configuration
################################################################

[acme]
email = "info@enkryptio.com"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
acmeLogging = true
OnHostRule = true

[acme.httpChallenge]
entryPoint = "http"
