version: '3.6'

networks:
  web:
    external: true

services:

  traefik:
    image: traefik:1.6.2-alpine
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.docker/config/traefik/traefik.dev.toml:/etc/traefik/traefik.toml
    networks:
      - web
    ports:
      - 80:80
      - 81:81

  ethvm:
    build:
      context: ./client
      dockerfile: ../.docker/images/client/Dockerfile
    restart: unless-stopped
    volumes:
      - ./client:/var/ethvm
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.default.protocol=http"
      - "traefik.frontend.rule=Host:ethvm.lan"
      - "traefik.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin:*||Access-Control-Allow-Credentials:true"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.backend=ethvm"
    environment:
      - ETHVM_HOST=0.0.0.0
      - ETHVM_PORT=80
      - ETVHM_DOCKER=true

  ethvm_socket_server:
    build:
      context: ./server
      dockerfile: ../.docker/images/server/Dockerfile
    restart: unless-stopped
    volumes:
      - ./server:/var/ethvm-server
    depends_on:
      - geth
      - redis
      - rethinkdb
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.default.protocol=http"
      - "traefik.frontend.rule=Host:ws.ethvm.lan"
      - "traefik.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin:http://ethvm.lan||Access-Control-Allow-Credentials:true"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.backend=ethvm_socket_server"

  redis:
    image: redis:4.0.9-alpine
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.default.protocol=http"
      - "traefik.frontend.rule=Host:redis.ethvm.lan"
      - "traefik.port=6379"
      - "traefik.backend=redis"

  rethinkdb:
    image: rethinkdb:2.3.6
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.default.protocol=http"
      - "traefik.frontend.rule=Host:rethink.ethvm.lan"
      - "traefik.port=28015"
      - "traefik.backend=rethinkdb"
      - "traefik.dashboard.frontend.rule=Host:rethink.dashboard.ethvm.lan"
      - "traefik.dashboard.protocol=http"
      - "traefik.dashboard.backend=ethvm_socket_server"
      - "traefik.dashboard.port=8080"

  geth:
    build:
      context: ./eth
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - rethinkdb
    volumes:
      - ./.docker/volumes/geth/:/geth
      - ./.docker/config/geth/genesis.json:/genesis.json
      - ./.docker/config/geth/keystore/UTC--2018-07-06T11-16-07.166Z--84baabad835e6ca9252658cd6eae0152f6330c09:/geth/keystore/UTC--2018-07-06T11-16-07.166Z--84baabad835e6ca9252658cd6eae0152f6330c09
    networks:
      - web
    ports:
      - 9545:9545
    labels:
      - "traefik.enable=true"
      - "traefik.default.protocol=http"
      - "traefik.frontend.rule=Host:geth.ethvm.lan"
      - "traefik.port=9545"
      - "traefik.backend=geth"
    environment:
      - RETHINKDB_URL=http://rethinkdb:28015
    command:
      - /bin/sh
      - -c
      - |
        geth --datadir="/geth/" --ethvm init /genesis.json
        geth --datadir="/geth/" --networkid 1234 --etherbase '0x84baabad835e6ca9252658cd6eae0152f6330c09' --mine --minerthreads 1 --ethvm --gcmode archive --rpc --rpcaddr '0.0.0.0' --rpcport 9545 --syncmode full --nodiscover --nousb
