---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: ethvm
  name: traefik-config
data:
  traefik.toml: |
    defaultEntryPoints = ["http","https"]
    debug = false
    logLevel = "INFO"

    [entryPoints]
      [entryPoints.http]
        address = ":80"
        compress = true
        [entryPoints.http.redirect]
        entryPoint = "https"
      [entryPoints.https]
        address = ":443"
        compress = true
        [entryPoints.https.tls]

    [kubernetes]

    [ping]
      entryPoint = "http"

    [accessLog]

    [acme]
      email = "it@enkryptio.com"
      storage = "/etc/traefik/acme/account"
      acmeLogging = true
      entryPoint = "https"
      OnHostRule = true
      [acme.httpChallenge]
        entryPoint="http"

---

apiVersion: v1
kind: Service
metadata:
  namespace: ethvm
  name: traefik-ingress-service
spec:
  selector:
    app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 80
      name: web
    - protocol: TCP
      port: 443
      name: https
  type: LoadBalancer
  #type: NodePort # Enable it in minikube

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: ethvm
  name: traefik-ingress-controller
  labels:
    app: traefik-ingress-lb
spec:
  replicas: 1
  serviceName: traefik-ingress-service
  selector:
    matchLabels:
      app: traefik-ingress-lb
  template:
    metadata:
      labels:
        app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      terminationGracePeriodSeconds: 60
      volumes:
        - name: config
          configMap:
            name: traefik-config
      containers:
      - image: traefik:1.6.2-alpine
        name: traefik-ingress-lb
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: config
          mountPath: /etc/traefik/config
        - name: acme-storage-volume
          mountPath: /etc/traefik/acme
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        args:
        - --configFile=/etc/traefik/config/traefik.toml
  volumeClaimTemplates:
  - metadata:
      name: acme-storage-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi
