---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-account
  namespace: kube-system
automountServiceAccountToken: false

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik-ingress-cr
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik-ingress-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-cr
subjects:
- kind: ServiceAccount
  name: traefik-ingress-account
  namespace: kube-system

---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: traefik-config
data:
  traefik.toml: |
    defaultEntryPoints = ["http","https"]
    debug = false
    logLevel = "INFO"

    [entryPoints]
      [entryPoints.http]
        address = ":80"
        compress = true
        [entryPoints.http.redirect]
        entryPoint = "https"
      [entryPoints.https]
        address = ":443"
        compress = true
        [entryPoints.https.tls]

    [kubernetes]

    [ping]
      entryPoint = "http"

    [accessLog]

    [acme]
      email = "it@enkryptio.com"
      storage = "/etc/traefik/acme/account"
      acmeLogging = true
      entryPoint = "https"
      OnHostRule = true
      [acme.httpChallenge]
        entryPoint="http"

---

apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: traefik-ingress-service
spec:
  selector:
    app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 80
      name: web
    - protocol: TCP
      port: 443
      name: https
  # type: LoadBalancer
  # loadBalancerIP: xx.xx.xx.xx
  type: NodePort # Enable it in minikube

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: kube-system
  name: traefik-ingress-controller
  labels:
    app: traefik-ingress-lb
spec:
  replicas: 1
  serviceName: traefik-ingress-service
  selector:
    matchLabels:
      app: traefik-ingress-lb
  template:
    metadata:
      labels:
        app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      containers:
      - image: traefik:1.6.2-alpine
        name: traefik-ingress-lb
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: config
          mountPath: /etc/traefik/config
        - name: traefik-storage-volume
          mountPath: /etc/traefik/acme
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        args:
        - --configFile=/etc/traefik/config/traefik.toml
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
      volumes:
      - name: config
        configMap:
          name: traefik-config
      serviceAccountName: traefik-ingress-account
      terminationGracePeriodSeconds: 60
  volumeClaimTemplates:
  - metadata:
      name: traefik-storage-volume
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 25Mi
